### ISSUE TITLE
improve readability of numpy arrays

### ISSUE THREAD

**Issue by cknoll** [cknoll/ipydex#2]
default display for an numpy array has bad readability. Sympy matrices are formated significantly better.

It would be nice, if there is a way to cast numpy arrays to matrices before displaying them (or to achieve nice readability another way).

**Comment by mfr13** [comment]
suggestion to improve readability of numpy arrays without using sympy matrices:

if the array consists of multiple rows (the string contains some '\n'):
	place in front of each '\n' an indent (4 + len(lhs) spaces)

**Comment by cknoll** [comment]
This was a good suggestion @mfr13.
See cell 11
http://nbviewer.jupyter.org/github/cknoll/ipydex/blob/master/examples/displaytools-example.ipynb
