### ISSUE TITLE
Installation on google colab

### ISSUE THREAD

**Issue by kHarshit** [cknoll/ipydex#7]
Hi,

I'm trying to use this extension on google colab, however, it doesn't work.

Steps I'm following:

```
# install nbextensions
!pip install jupyter_contrib_nbextensions
# install js and CSS
!jupyter contrib nbextension install --user
# install ipydex
`!pip install ipydex`
# enable ipydex
`!jupyter nbextension enable ipydex.displaytools`
```

It doesn't get enabled, the error I'm getting:

```
Enabling notebook extension ipydex.displaytools...
Paths used for configuration of notebook: 
    	/root/.jupyter/nbconfig/notebook.json
Paths used for configuration of notebook: 
    	
      - Validating: problems found:
        - require?  X ipydex.displaytools
Paths used for configuration of notebook: 
    	/root/.jupyter/nbconfig/notebook.json
```

However, if I try enabling another extension, say, hinterland or codefolding, it works:

```
!jupyter nbextension enable codefolding/main
Enabling notebook extension codefolding/main...
Paths used for configuration of notebook: 
    	/root/.jupyter/nbconfig/notebook.json
Paths used for configuration of notebook: 
    	
      - Validating: OK
Paths used for configuration of notebook: 
    	/root/.jupyter/nbconfig/notebook.json
```

**Comment by cknoll** [comment]
I tried the following in colab: `!pip install ipydex` and then `%load_ext ipydex.displaytools` and the extension worked. @kHarshit could you try that and report? If that works for you, you can close the issue.

I had not yet heard about *jupyter_contrib_nbextensions* before and I am currently not aware what exactly `!jupyter nbextension ... ` does. The extension *ipydex.displaytools* uses the vanilla extension loading mechanism provided by jupyter notebook.

However, *jupyter_contrib_nbextensions* seems interesting and I should have a deeper look.

**Comment by kHarshit** [comment]
Yes, it works using `%load_ext`, thanks.
